from .mask_nodes import NODE_CLASS_MAPPINGS as MASK_NODE_CLASS_MAPPINGS
from .mask_nodes import NODE_DISPLAY_NAME_MAPPINGS as MASK_NODE_DISPLAY_NAME_MAPPINGS
from .image_nodes import NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS
from .image_nodes import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS
from .face_nodes import NODE_CLASS_MAPPINGS as FACE_NODE_CLASS_MAPPINGS
from .face_nodes import NODE_DISPLAY_NAME_MAPPINGS as FACE_NODE_DISPLAY_NAME_MAPPINGS

# 合并所有节点
NODE_CLASS_MAPPINGS = {
    **MASK_NODE_CLASS_MAPPINGS,
    **IMAGE_NODE_CLASS_MAPPINGS,
    **FACE_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MASK_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **FACE_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
